### PR TITLE
WIP: Reimplement the bundle with jax-rs-pac4j

### PR DESCRIPTION
**Pull request by victornoel**
Hi,

As promised some time ago, I made a jax-rs integration of pac4j that works well with Jersey and dropwizard (see https://github.com/pac4j/jersey-pac4j/pull/1, the name of the project will change to jax-rs-pac4j).

So here is a reimplementation of the dropwizard-pac4j bundle.

I think this should simply replace the previous one because it adheres much better to the way dropwizard is meant to work: jax-rs-pac4j provides annotations to inject the filters on specific resource methods on top of the possibility to have multiple global filters for the whole application.

So with this new implementation of dropwizard-pac4j, we can do what was doable before (i.e., having one global SecurityFilter) and more (i.e. having multiple global SecurityFilter + injection of SecurityFilter, LogoutFilter and CallbackFilter).

The global filters are configured in the yml file.
The pac4j config must be configured programmatically using ConfigSingleton (provided by pac4j) in the application run method (because sharing an object between the application run method and the bundle run method is really complex in dropwizard). I validated that it was correct to do so (i.e. the content of the config is never used before the filters are actually processing requests).

I updated the tests, except for the Pac4jBundleTest because its content was almost the same as reading the java file… I can readd it, but I don't see the point.

Finally, it relies on SNAPSHOT version of pac4j (need some bugfixes) and jax-rs-pac4j (not yet released).

I'm of course open to any review and anyway we will need to wait for jax-rs-pac4j to be merged (and deployed) before this can be merged too :)

### CODE REVIEW

**Comment by evnm** [comment]
This is great! The J2E integration was a bit of a hack to begin with, so the JAX-RS/Jersey support is a much better fit for Dropwizard applications. This definitely moves us in the direction of providing the least amount of glue to connect a Dropwizard configuration file to pac4j.

Removing `Pac4jBundleTest` is fine. No sense keeping it around unnecessarily.

Let's reconvene on this PR once `jax-rs-pac4j` merges and a new version of `pac4j` is released.

**Comment by leleuj** [comment]
`jax-rs-pac4j` is now available.

@evnm this PR looks good to me as well. I think we should merge it now (and not wait for next `pac4j` release which will be in any case a minor version)

**Comment by victornoel** [comment]
Yes, it would be great if we can release a version of dropwizard-pac4j after 1.9.3 is released.

By the way @evnm, is this maven artifact deployed to maven central like the rest of the dropwizard artifacts?

**Comment by leleuj** [comment]
If we move it under the pac4j organization, we'll need to change the `groupId` to `org.pac4j` so that we can release it.

**Comment by evnm** [comment]
@victornoel, no artifacts have been released for this library. I held off on releasing anything until APIs stabilized and we wanted to move forward with a 0.0.1 stable release.

@leleuj, I will take care of updating the package names after migrating the library over to the pac4j org.

**Comment by victornoel** [comment]
Thanks guys :)

**Pull request merged**
